[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 90
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
healthcheckInterval = 15
healthcheckStartPeriod = 45

[variables]
NODE_ENV = "production"
PORT = "8080"
RAILWAY_STATIC_URL = "https://${RAILWAY_STATIC_URL}" 